# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76389da6c33d68d2b4327e43f90387db45454f08aeda7d4fc59ac8c5103b8550262edb86f73b5533fb6d0138fbfb228b57244db15d6c6c95dd5efb8a0cf9fa82

test:
  secret_key_base: e4d93394876d4a6c1814fe3d7fd241cd8eeb740e103736954565fe5bb80bec95e998c11348669eb568e2c00307586f8a5c47aa460d53abe31e76ed10b1964346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
